allow-branch = ["main"]
consolidate-commits = false
pre-release-commit-message = "chore: release {{crate_name}}-v{{version}}"
tag-message = "{{crate_name}} version {{version}}"
tag-name = "{{prefix}}v{{version}}"
