allow-branch = ["main"]
consolidate-commits = false
pre-release-commit-message = "{{crate_name}}: release version {{version}}"
tag-message = "{{crate_name}} version {{version}}"
tag-name = "{{prefix}}v{{version}}"
