blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/koushiro/rust-bips/discussions/new?category=q-a
    about: Please ask questions about usage and development here.
