[workspace]
members = []
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/koushiro/rust-bips"
homepage = "https://github.com/koushiro/rust-bips"
rust-version = "1.85.0"

[package]
name = "bip0032"
version = "0.0.0"
authors = ["koushiro <koushiro.cqx@gmail.com>"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

description = "Another Rust implementation of BIP-0032 standard"
readme = "README.md"
documentation = "https://docs.rs/bip0032"
keywords = ["bip32", "bitcoin", "crypto"]
categories = ["cryptography", "no-std"]

[dependencies]

[features]
default = ["std"]
std = []
